### ISSUE TITLE
Error Vmas Transport

### ISSUE THREAD

**Issue by prinshul** [facebookresearch/BenchMARL#54] opened 2024-01-20 08:23 UTC
>python fine_tuned/vmas/vmas_run.py algorithm=mappo task=vmas/transport

Error executing job with overrides: ['algorithm=mappo', 'task=vmas/transport']
Traceback (most recent call last):
  File "/hdd3/marl_new/BenchMARL/fine_tuned/vmas/vmas_run.py", line 31, in <module>
    hydra_experiment()
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/iitdpc/miniconda3/envs/marl_bench/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/hdd3/marl_new/BenchMARL/fine_tuned/vmas/vmas_run.py", line 25, in hydra_experiment
    experiment: Experiment = load_experiment_from_hydra(cfg, task_name=task_name)
  File "/hdd3/marl_new/BenchMARL/benchmarl/hydra_config.py", line 37, in load_experiment_from_hydra
    return Experiment(
  File "/hdd3/marl_new/BenchMARL/benchmarl/experiment/experiment.py", line 323, in __init__
    self._setup()
  File "/hdd3/marl_new/BenchMARL/benchmarl/experiment/experiment.py", line 344, in _setup
    self._setup_collector()
  File "/hdd3/marl_new/BenchMARL/benchmarl/experiment/experiment.py", line 447, in _setup_collector
    self.collector = SyncDataCollector(
  File "/hdd3/marl_new/BenchMARL/torchrl_custom/collectors/collectors.py", line 636, in __init__
    self._tensordict = env.reset()
  File "/hdd3/marl_new/BenchMARL/torchrl_custom/envs/common.py", line 1495, in reset
    return self._reset_proc_data(tensordict, tensordict_reset)
  File "/hdd3/marl_new/BenchMARL/torchrl_custom/envs/transforms/transforms.py", line 765, in _reset_proc_data
    self._reset_check_done(tensordict, tensordict_reset)
  File "/hdd3/marl_new/BenchMARL/torchrl_custom/envs/common.py", line 1547, in _reset_check_done
    raise RuntimeError(
RuntimeError: The done entry 'done' was (partially) True after a call to reset() in env TransformedEnv(
    env=VmasEnv(num_envs=600, n_agents=4, batch_size=torch.Size([600]), device=cuda:0) (scenario=transport),
    transform=Compose(
            RewardSum(keys=[('agents', 'reward')]))).

**Comment by matteobettini** [comment] 2024-01-20 08:36
Duplicate of #43 

this should be fixed, upgrade your vmas version

**Closed** 2024-01-20 17:27 UTC
